repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2
        args: [--fix]

  - repo: https://github.com/crate-ci/typos
    rev: v1.30.2
    hooks:
      - id: typos
        args: [--write-changes]
        files: ^(.*\.md$|i18n/.*\.toml$)

  - repo: local
    hooks:
      - id: taplo
        name: taplo fmt
        language: system
        entry: taplo fmt
        types: [toml]

      - id: bibtex-tidy
        name: bibtex-tidy
        language: node
        additional_dependencies: [bibtex-tidy]
        entry: bibtex-tidy --modify
        files: \.bib$
